### ISSUE TITLE
Automating javascript plugins

### ISSUE THREAD

**Issue by jacoobes** [sern-handler/awesome-plugins#11]
Could we use a tool like babel to transform typescript code into javascript?
https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs
 https://babeljs.io/docs/en/babel-plugin-transform-flow-strip-types

**Comment by jacoobes** [comment]
or, just run tsc on it. Either one could help streamline and mirror typescript plugins to javascript

**Comment by EvolutionX-10** [comment]
haven't seen babel yet, but can be good amount of issues with tsc

**Comment by Benzo-Fury** [comment]
Would be much better for people running in JavaScript (everyone but me) if it was automatically done on GitHub. Not sure if that's what babel does or not but there would be something on GitHub to do that.

**Comment by jacoobes** [comment]
Yes was thinking it if it was possible to use a github action to automate.
- on pull request merge, 
- some gh action runs babel and transpiles the typescript source code into javascript.

**Comment by EvolutionX-10** [comment]
Done
